// astro-sitecore-jss/packages/astro-sitecore-jss-sample/src/components/integrations/vue/ContentBlock.vue
<template>
  <div class="contentBlock">
    <sc-text tag="h6" class="contentTitle" :field="fields.heading" />
    <sc-rich-text class="contentDescription" :field="fields.description" />
  </div>
</template>

<script>
import { Text, RichText } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'ContentBlock',
  props: {
    fields: {
      type: Object,
      default: () => ({}),
    },
    params: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    ScRichText: RichText,
  },
};
</script>

// astro-sitecore-jss/packages/astro-sitecore-jss-sample/src/components/integrations/angular/ContentBlock/content-block.component.ts
import { NgIf } from '@angular/common';
import type { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';
import { Component, Input } from '@angular/core';
import { TextDirective } from '../Standalone/text.directive';
import { RichTextDirective } from '../Standalone/rich-text.directive';

@Component({
  standalone: true,
  selector: 'app-content-block',
  templateUrl: './content-block.component.html',
  imports: [NgIf, TextDirective, RichTextDirective]

})
export class ContentBlockComponent {
  @Input() fields: ComponentRendering | any | undefined;
}


<div class="contentBlock">
  <h6 class="contentTitle" *scText="fields?.heading"></h6>
  <div class="contentDescription" *scRichText="fields?.description"></div>
</div>
