// astro-sitecore-jss/packages/astro-sitecore-jss-sample/src/components/integrations/react/ContentBlock.jsx
import React from 'react';
import { Text, RichText } from '@sitecore-jss/sitecore-jss-react';
//import { Placeholder } from '@sitecore-jss/sitecore-jss-react';
//import ComponentFactory from "./ComponentFactory";

/**
 * A simple Content Block component, with a heading and rich text block.
 * This is the most basic building block of a content site, and the most basic
 * JSS component that's useful.
 */
const ContentBlock = (props) => {
  const fields = props.fields;

  return (
    <div className="contentBlock">
      <Text tag="h6" className="contentTitle" field={fields.heading} />
      <RichText className="contentDescription" field={fields.description} />
      {/*
      Example of using a placeholder inside React compoents
      <Placeholder name="react" rendering={props.rendering} componentFactory={ComponentFactory} />
      */}
    </div>
  );
}

export default ContentBlock;

// astro-sitecore-jss/packages/astro-sitecore-jss-sample/src/components/integrations/vue/ContentBlock.vue
<template>
  <div class="contentBlock">
    <sc-text tag="h6" class="contentTitle" :field="fields.heading" />
    <sc-rich-text class="contentDescription" :field="fields.description" />
  </div>
</template>

<script>
import { Text, RichText } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'ContentBlock',
  props: {
    fields: {
      type: Object,
      default: () => ({}),
    },
    params: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    ScRichText: RichText,
  },
};
</script>
