// astro-sitecore-jss/packages/astro-sitecore-jss-sample/src/components/integrations/vue/Counter.vue
<template>
    <div className="flex">
      <div>
        Count: {{ count }}
      </div>
      <button v-on:click="count += 1" class="btn btn-primary m-2">
        Increment
      </button>
      <button v-on:click="count -= 1" class="btn btn-primary m-2">
        Decrement
      </button>
    </div>
</template>

<script>

export default {
  name: 'Counter',
  props: {
    count: {
      type: Number,
      default: 0,
    }
  }
};
</script>

// astro-sitecore-jss/packages/astro-vue-sitecore-jss-sample/src/components/integrations/react/Counter.jsx
import React, {useState} from "react";

const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <div className="flex">
      <div>
        Count: {count}
      </div>
      <button onClick={() => setCount(count + 1)} className="btn btn-primary m-2">
        Increment
      </button>
      <button onClick={() => setCount(count - 1)} className="btn btn-primary m-2">
        Decrement
      </button>
    </div>
  );
};

export default Counter;
