// astro-sitecore-jss/packages/astro-vue-sitecore-jss-sample/src/components/integrations/react/Counter.jsx
import React, {useState} from "react";

const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <div className="flex">
      <div>
        Count: {count}
      </div>
      <button onClick={() => setCount(count + 1)} className="btn btn-primary m-2">
        Increment
      </button>
      <button onClick={() => setCount(count - 1)} className="btn btn-primary m-2">
        Decrement
      </button>
    </div>
  );
};

export default Counter;

// astro-sitecore-jss/packages/astro-sitecore-jss-sample/src/components/integrations/angular/Counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  standalone: true,
})
export default class CounterComponent {
  count!: number;

  ngOnInit() {
    this.count = 0;
  }
}
<div className="flex">
  <div>
    Count: {{count}}
  </div>
  <button (click)="count = count + 1" class="btn btn-primary m-2">
    Increment
  </button>
  <button (click)="count = count - 1" class="btn btn-primary m-2">
    Decrement
  </button>
</div>
